name: Deploy Dist

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Prepare dist branch
        run: |
          # Fetch the dist branch
          git fetch origin dist:dist || git checkout --orphan dist
          git checkout dist

      - name: Copy dist contents
        run: |
          # Clear existing contents in the root of dist branch
          rm -rf *
          # Copy new contents from the dist directory
          cp -r dist/* .

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Copy dist folder contents" || echo "No changes to commit"
          git push origin dist --force
