name: Deploy Dist

on:
  push:
    branches:
      - master  # Trigger on pushes to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dist branch
        uses: actions/checkout@v2
        with:
          ref: dist

      - name: Set up Git
        run: |
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"

      - name: Checkout master branch
        run: |
          git fetch origin master  # Replace 'master' with 'main' if necessary
          git checkout master || git checkout -b master

      - name: Remove existing files in the dist branch
        run: |
          rm -rf * || true  # Clears the working directory

      - name: Copy all files from the dist directory in master
        run: |
          git checkout master -- dist/* || echo "No files to copy from dist directory."

      - name: Stage changes
        run: |
          git add .

      - name: Commit changes
        run: |
          git commit -m "Copy all files from dist directory of master to root of dist branch" || echo "No changes to commit"

      - name: Push changes to dist branch
        run: |
          git push origin dist
